<?php

namespace AlibabaCloud\Hitsdb;

/**
 * @method string getResourceOwnerId()
 * @method $this withResourceOwnerId($value)
 * @method string getPhoenixCoreNum()
 * @method $this withPhoenixCoreNum($value)
 * @method string getPhoenixCoreSpec()
 * @method $this withPhoenixCoreSpec($value)
 * @method string getClientToken()
 * @method $this withClientToken($value)
 * @method string getUpgradeType()
 * @method $this withUpgradeType($value)
 * @method string getTsdbSpec()
 * @method $this withTsdbSpec($value)
 * @method string getFilestoreSpec()
 * @method $this withFilestoreSpec($value)
 * @method string getSecurityToken()
 * @method $this withSecurityToken($value)
 * @method string getTsdbNum()
 * @method $this withTsdbNum($value)
 * @method string getLindormSpec()
 * @method $this withLindormSpec($value)
 * @method string getSolrNum()
 * @method $this withSolrNum($value)
 * @method string getColdStorage()
 * @method $this withColdStorage($value)
 * @method string getSolrSpec()
 * @method $this withSolrSpec($value)
 * @method string getResourceOwnerAccount()
 * @method $this withResourceOwnerAccount($value)
 * @method string getOwnerAccount()
 * @method $this withOwnerAccount($value)
 * @method string getFilestoreNum()
 * @method $this withFilestoreNum($value)
 * @method string getOwnerId()
 * @method $this withOwnerId($value)
 * @method string getLindormNum()
 * @method $this withLindormNum($value)
 * @method string getCoreSpec()
 * @method $this withCoreSpec($value)
 * @method string getCoreNum()
 * @method $this withCoreNum($value)
 * @method string getLtsCoreNum()
 * @method $this withLtsCoreNum($value)
 * @method string getInstanceId()
 * @method $this withInstanceId($value)
 * @method string getLtsCoreSpec()
 * @method $this withLtsCoreSpec($value)
 * @method string getClusterStorage()
 * @method $this withClusterStorage($value)
 * @method string getZoneId()
 * @method $this withZoneId($value)
 */
class UpgradeLindormInstance extends Rpc
{
}
