<?php

namespace AlibabaCloud\Sas;

/**
 * @method string getType()
 * @method $this withType($value)
 * @method string getCreateTsStart()
 * @method $this withCreateTsStart($value)
 * @method string getContainerFieldName()
 * @method $this withContainerFieldName($value)
 * @method string getSourceIp()
 * @method $this withSourceIp($value)
 * @method string getTag()
 * @method $this withTag($value)
 * @method string getModifyTsEnd()
 * @method $this withModifyTsEnd($value)
 * @method string getLevel()
 * @method $this withLevel($value)
 * @method string getResource()
 * @method $this withResource($value)
 * @method string getGroupId()
 * @method $this withGroupId($value)
 * @method string getAliasName()
 * @method $this withAliasName($value)
 * @method string getInstanceId()
 * @method $this withInstanceId($value)
 * @method string getName()
 * @method $this withName($value)
 * @method string getIds()
 * @method $this withIds($value)
 * @method string getCreateTsEnd()
 * @method $this withCreateTsEnd($value)
 * @method string getNecessity()
 * @method $this withNecessity($value)
 * @method string getUuids()
 * @method $this withUuids($value)
 * @method string getRepoId()
 * @method $this withRepoId($value)
 * @method string getStatusList()
 * @method $this withStatusList($value)
 * @method string getTargetType()
 * @method $this withTargetType($value)
 * @method string getCveId()
 * @method $this withCveId($value)
 * @method string getRemark()
 * @method $this withRemark($value)
 * @method string getRepoNamespace()
 * @method $this withRepoNamespace($value)
 * @method string getContainerFieldValue()
 * @method $this withContainerFieldValue($value)
 * @method string getPageSize()
 * @method $this withPageSize($value)
 * @method string getDigest()
 * @method $this withDigest($value)
 * @method string getModifyTsStart()
 * @method $this withModifyTsStart($value)
 * @method string getLang()
 * @method $this withLang($value)
 * @method string getDealed()
 * @method $this withDealed($value)
 * @method string getCurrentPage()
 * @method $this withCurrentPage($value)
 * @method string getBatchName()
 * @method $this withBatchName($value)
 * @method string getRepoName()
 * @method $this withRepoName($value)
 * @method string getRepoInstanceId()
 * @method $this withRepoInstanceId($value)
 * @method string getRepoRegionId()
 * @method $this withRepoRegionId($value)
 */
class DescribeImageVulList extends Rpc
{
}
