<?php

namespace AlibabaCloud\Sas;

/**
 * @method string getType()
 * @method $this withType($value)
 * @method string getLastTsEnd()
 * @method $this withLastTsEnd($value)
 * @method string getCreateTsStart()
 * @method $this withCreateTsStart($value)
 * @method string getSourceIp()
 * @method $this withSourceIp($value)
 * @method string getImageTag()
 * @method $this withImageTag($value)
 * @method string getLevel()
 * @method $this withLevel($value)
 * @method string getGroupId()
 * @method $this withGroupId($value)
 * @method string getOrderBy()
 * @method $this withOrderBy($value)
 * @method string getAliasName()
 * @method $this withAliasName($value)
 * @method string getPatchId()
 * @method $this withPatchId($value)
 * @method string getName()
 * @method $this withName($value)
 * @method string getCreateTsEnd()
 * @method $this withCreateTsEnd($value)
 * @method string getNecessity()
 * @method $this withNecessity($value)
 * @method string getUuids()
 * @method $this withUuids($value)
 * @method string getRepoId()
 * @method $this withRepoId($value)
 * @method string getStatusList()
 * @method $this withStatusList($value)
 * @method string getCveId()
 * @method $this withCveId($value)
 * @method string getRemark()
 * @method $this withRemark($value)
 * @method string getRepoNamespace()
 * @method $this withRepoNamespace($value)
 * @method string getImageDigest()
 * @method $this withImageDigest($value)
 * @method string getPageSize()
 * @method $this withPageSize($value)
 * @method string getLang()
 * @method $this withLang($value)
 * @method string getLastTsStart()
 * @method $this withLastTsStart($value)
 * @method string getDirection()
 * @method $this withDirection($value)
 * @method string getDealed()
 * @method $this withDealed($value)
 * @method string getCurrentPage()
 * @method $this withCurrentPage($value)
 * @method string getSearchTags()
 * @method $this withSearchTags($value)
 * @method string getRepoName()
 * @method $this withRepoName($value)
 * @method string getRepoInstanceId()
 * @method $this withRepoInstanceId($value)
 * @method string getImageLayer()
 * @method $this withImageLayer($value)
 * @method string getRepoRegionId()
 * @method $this withRepoRegionId($value)
 */
class DescribeImageGroupedVulList extends Rpc
{
}
