<?php

namespace AlibabaCloud\Dts;

/**
 * @method string getCheckpoint()
 * @method $this withCheckpoint($value)
 * @method string getSourceEndpointUserName()
 * @method $this withSourceEndpointUserName($value)
 * @method string getDelayPhone()
 * @method $this withDelayPhone($value)
 * @method string getSourceEndpointIP()
 * @method $this withSourceEndpointIP($value)
 * @method string getErrorPhone()
 * @method $this withErrorPhone($value)
 * @method string getDestinationEndpointUserName()
 * @method $this withDestinationEndpointUserName($value)
 * @method string getDtsJobId()
 * @method $this withDtsJobId($value)
 * @method string getDbList()
 * @method $this withDbList($value)
 * @method string getDestinationEndpointOracleSID()
 * @method $this withDestinationEndpointOracleSID($value)
 * @method string getDestinationEndpointPort()
 * @method $this withDestinationEndpointPort($value)
 * @method string getSourceEndpointPassword()
 * @method $this withSourceEndpointPassword($value)
 * @method string getOwnerId()
 * @method $this withOwnerId($value)
 * @method string getJobType()
 * @method $this withJobType($value)
 * @method string getDelayRuleTime()
 * @method $this withDelayRuleTime($value)
 * @method string getDestinationEndpointIP()
 * @method $this withDestinationEndpointIP($value)
 * @method string getSourceEndpointInstanceType()
 * @method $this withSourceEndpointInstanceType($value)
 * @method string getDtsJobName()
 * @method $this withDtsJobName($value)
 * @method string getDtsInstanceId()
 * @method $this withDtsInstanceId($value)
 * @method string getSynchronizationDirection()
 * @method $this withSynchronizationDirection($value)
 * @method string getSourceEndpointRegion()
 * @method $this withSourceEndpointRegion($value)
 * @method string getDelayNotice()
 * @method $this withDelayNotice($value)
 * @method string getDestinationEndpointInstanceType()
 * @method $this withDestinationEndpointInstanceType($value)
 * @method string getDataInitialization()
 * @method $this withDataInitialization($value)
 * @method string getSourceEndpointInstanceID()
 * @method $this withSourceEndpointInstanceID($value)
 * @method string getStructureInitialization()
 * @method $this withStructureInitialization($value)
 * @method string getSourceEndpointOwnerID()
 * @method $this withSourceEndpointOwnerID($value)
 * @method string getSourceEndpointDatabaseName()
 * @method $this withSourceEndpointDatabaseName($value)
 * @method string getDestinationEndpointRegion()
 * @method $this withDestinationEndpointRegion($value)
 * @method string getReserve()
 * @method $this withReserve($value)
 * @method string getDataSynchronization()
 * @method $this withDataSynchronization($value)
 * @method string getDestinationEndpointEngineName()
 * @method $this withDestinationEndpointEngineName($value)
 * @method string getDestinationEndpointInstanceID()
 * @method $this withDestinationEndpointInstanceID($value)
 * @method string getSourceEndpointPort()
 * @method $this withSourceEndpointPort($value)
 * @method string getSourceEndpointOracleSID()
 * @method $this withSourceEndpointOracleSID($value)
 * @method string getDestinationEndpointDataBaseName()
 * @method $this withDestinationEndpointDataBaseName($value)
 * @method string getErrorNotice()
 * @method $this withErrorNotice($value)
 * @method string getSourceEndpointRole()
 * @method $this withSourceEndpointRole($value)
 * @method string getDestinationEndpointPassword()
 * @method $this withDestinationEndpointPassword($value)
 * @method string getSourceEndpointEngineName()
 * @method $this withSourceEndpointEngineName($value)
 */
class ConfigureDtsJob extends Rpc
{
}
