<?php

namespace AlibabaCloud\Dts;

/**
 * @method string getSourceEndpointRegion()
 * @method $this withSourceEndpointRegion($value)
 * @method string getCheckpoint()
 * @method $this withCheckpoint($value)
 * @method string getSubscriptionInstanceVSwitchId()
 * @method $this withSubscriptionInstanceVSwitchId($value)
 * @method string getDelayNotice()
 * @method $this withDelayNotice($value)
 * @method string getSourceEndpointInstanceID()
 * @method $this withSourceEndpointInstanceID($value)
 * @method string getSourceEndpointUserName()
 * @method $this withSourceEndpointUserName($value)
 * @method string getSourceEndpointOwnerID()
 * @method $this withSourceEndpointOwnerID($value)
 * @method string getDelayPhone()
 * @method $this withDelayPhone($value)
 * @method string getSubscriptionDataTypeDML()
 * @method $this withSubscriptionDataTypeDML($value)
 * @method string getSourceEndpointDatabaseName()
 * @method $this withSourceEndpointDatabaseName($value)
 * @method string getSourceEndpointIP()
 * @method $this withSourceEndpointIP($value)
 * @method string getErrorPhone()
 * @method $this withErrorPhone($value)
 * @method string getReserve()
 * @method $this withReserve($value)
 * @method string getDtsJobId()
 * @method $this withDtsJobId($value)
 * @method string getDbList()
 * @method $this withDbList($value)
 * @method string getSubscriptionInstanceNetworkType()
 * @method $this withSubscriptionInstanceNetworkType($value)
 * @method string getSubscriptionDataTypeDDL()
 * @method $this withSubscriptionDataTypeDDL($value)
 * @method string getSourceEndpointPassword()
 * @method $this withSourceEndpointPassword($value)
 * @method string getSourceEndpointPort()
 * @method $this withSourceEndpointPort($value)
 * @method string getSubscriptionInstanceVPCId()
 * @method $this withSubscriptionInstanceVPCId($value)
 * @method string getDelayRuleTime()
 * @method $this withDelayRuleTime($value)
 * @method string getSourceEndpointInstanceType()
 * @method $this withSourceEndpointInstanceType($value)
 * @method string getDtsJobName()
 * @method $this withDtsJobName($value)
 * @method string getSourceEndpointOracleSID()
 * @method $this withSourceEndpointOracleSID($value)
 * @method string getErrorNotice()
 * @method $this withErrorNotice($value)
 * @method string getSourceEndpointRole()
 * @method $this withSourceEndpointRole($value)
 * @method string getDtsInstanceId()
 * @method $this withDtsInstanceId($value)
 * @method string getSourceEndpointEngineName()
 * @method $this withSourceEndpointEngineName($value)
 */
class ConfigureSubscription extends Rpc
{
}
