<?php

namespace AlibabaCloud\Cas;

/**
 * @method string getLeaderName()
 * @method $this withLeaderName($value)
 * @method string getCity()
 * @method $this withCity($value)
 * @method string getCountryCode()
 * @method $this withCountryCode($value)
 * @method string getLeaderEmail()
 * @method $this withLeaderEmail($value)
 * @method string getCompanyAddress()
 * @method $this withCompanyAddress($value)
 * @method string getCompanyCode()
 * @method $this withCompanyCode($value)
 * @method string getPersonEmail()
 * @method $this withPersonEmail($value)
 * @method string getProvince()
 * @method $this withProvince($value)
 * @method string getDomainAuthType()
 * @method $this withDomainAuthType($value)
 * @method string getLeaderPhone()
 * @method $this withLeaderPhone($value)
 * @method string getSourceIp()
 * @method $this withSourceIp($value)
 * @method string getCsrContent()
 * @method $this withCsrContent($value)
 * @method string getLang()
 * @method $this withLang($value)
 * @method string getPersonName()
 * @method $this withPersonName($value)
 * @method string getPersonIdCardNumber()
 * @method $this withPersonIdCardNumber($value)
 * @method string getOrderId()
 * @method $this withOrderId($value)
 * @method string getLeaderTitle()
 * @method $this withLeaderTitle($value)
 * @method string getPersonTitle()
 * @method $this withPersonTitle($value)
 * @method string getPostCode()
 * @method $this withPostCode($value)
 * @method string getCreateCsr()
 * @method $this withCreateCsr($value)
 * @method string getPersonPhone()
 * @method $this withPersonPhone($value)
 * @method string getCompanyName()
 * @method $this withCompanyName($value)
 * @method string getCompanyPhone()
 * @method $this withCompanyPhone($value)
 * @method string getCompanyType()
 * @method $this withCompanyType($value)
 * @method string getDomain()
 * @method $this withDomain($value)
 * @method string getPersonDepartment()
 * @method $this withPersonDepartment($value)
 */
class CreateOrderMaterial extends Rpc
{
}
