<?php

namespace AlibabaCloud\Emr;

/**
 * @method string getCronExpr()
 * @method $this withCronExpr($value)
 * @method string getPeriodic()
 * @method $this withPeriodic($value)
 * @method string getDescription()
 * @method $this withDescription($value)
 * @method string getAlertUserGroupBizId()
 * @method $this withAlertUserGroupBizId($value)
 * @method string getLifecycle()
 * @method $this withLifecycle($value)
 * @method string getHostName()
 * @method $this withHostName($value)
 * @method string getCreateCluster()
 * @method $this withCreateCluster($value)
 * @method string getEndSchedule()
 * @method $this withEndSchedule($value)
 * @method string getId()
 * @method $this withId($value)
 * @method string getAlertConf()
 * @method $this withAlertConf($value)
 * @method string getProjectId()
 * @method $this withProjectId($value)
 * @method string getParentFlowList()
 * @method $this withParentFlowList($value)
 * @method string getLogArchiveLocation()
 * @method $this withLogArchiveLocation($value)
 * @method string getAlertDingDingGroupBizId()
 * @method $this withAlertDingDingGroupBizId($value)
 * @method string getStartSchedule()
 * @method $this withStartSchedule($value)
 * @method string getClusterId()
 * @method $this withClusterId($value)
 * @method string getGraph()
 * @method $this withGraph($value)
 * @method string getName()
 * @method $this withName($value)
 * @method string getNamespace()
 * @method $this withNamespace($value)
 * @method string getStatus()
 * @method $this withStatus($value)
 * @method string getParentCategory()
 * @method $this withParentCategory($value)
 */
class ModifyFlowForWeb extends Rpc
{
}
