<?php

namespace AlibabaCloud\HBase;

/**
 * @method string getArchVersion()
 * @method $this withArchVersion($value)
 * @method string getClusterName()
 * @method $this withClusterName($value)
 * @method string getEngineVersion()
 * @method $this withEngineVersion($value)
 * @method string getLogDiskType()
 * @method $this withLogDiskType($value)
 * @method string getPrimaryVSwitchId()
 * @method $this withPrimaryVSwitchId($value)
 * @method string getLogInstanceType()
 * @method $this withLogInstanceType($value)
 * @method string getAutoRenewPeriod()
 * @method $this withAutoRenewPeriod($value)
 * @method string getPeriod()
 * @method $this withPeriod($value)
 * @method string getLogNodeCount()
 * @method $this withLogNodeCount($value)
 * @method string getSecurityIPList()
 * @method $this withSecurityIPList($value)
 * @method string getPeriodUnit()
 * @method $this withPeriodUnit($value)
 * @method string getCoreDiskType()
 * @method $this withCoreDiskType($value)
 * @method string getArbiterZoneId()
 * @method $this withArbiterZoneId($value)
 * @method string getClientToken()
 * @method $this withClientToken($value)
 * @method string getMultiZoneCombination()
 * @method $this withMultiZoneCombination($value)
 * @method string getPrimaryZoneId()
 * @method $this withPrimaryZoneId($value)
 * @method string getEngine()
 * @method $this withEngine($value)
 * @method string getStandbyVSwitchId()
 * @method $this withStandbyVSwitchId($value)
 * @method string getStandbyZoneId()
 * @method $this withStandbyZoneId($value)
 * @method string getMasterInstanceType()
 * @method $this withMasterInstanceType($value)
 * @method string getCoreNodeCount()
 * @method $this withCoreNodeCount($value)
 * @method string getLogDiskSize()
 * @method $this withLogDiskSize($value)
 * @method string getCoreInstanceType()
 * @method $this withCoreInstanceType($value)
 * @method string getCoreDiskSize()
 * @method $this withCoreDiskSize($value)
 * @method string getVpcId()
 * @method $this withVpcId($value)
 * @method string getPayType()
 * @method $this withPayType($value)
 * @method string getArbiterVSwitchId()
 * @method $this withArbiterVSwitchId($value)
 */
class EvaluateMultiZoneResource extends Rpc
{
}
