<?php

namespace AlibabaCloud\Vs;

/**
 * @method string getHlsTs()
 * @method $this withHlsTs($value)
 * @method string getOssEndpoint()
 * @method $this withOssEndpoint($value)
 * @method string getDescription()
 * @method $this withDescription($value)
 * @method string getOssFilePrefix()
 * @method $this withOssFilePrefix($value)
 * @method string getJpgOverwrite()
 * @method $this withJpgOverwrite($value)
 * @method string getStartTime()
 * @method $this withStartTime($value)
 * @method string getJpgOnDemand()
 * @method $this withJpgOnDemand($value)
 * @method string getId()
 * @method $this withId($value)
 * @method string getRetention()
 * @method $this withRetention($value)
 * @method string getShowLog()
 * @method $this withShowLog($value)
 * @method string getHlsM3u8()
 * @method $this withHlsM3u8($value)
 * @method string getOssBucket()
 * @method $this withOssBucket($value)
 * @method string getTransConfigsJSON()
 * @method $this withTransConfigsJSON($value)
 * @method string getEndTime()
 * @method $this withEndTime($value)
 * @method string getTrigger()
 * @method $this withTrigger($value)
 * @method string getOwnerId()
 * @method $this withOwnerId($value)
 * @method string getJpgSequence()
 * @method $this withJpgSequence($value)
 * @method string getMp4()
 * @method $this withMp4($value)
 * @method string getFlv()
 * @method $this withFlv($value)
 * @method string getName()
 * @method $this withName($value)
 * @method string getCallback()
 * @method $this withCallback($value)
 * @method string getInterval()
 * @method $this withInterval($value)
 * @method string getFileFormat()
 * @method $this withFileFormat($value)
 * @method string getRegion()
 * @method $this withRegion($value)
 */
class ModifyTemplate extends Rpc
{
}
