<?php

namespace AlibabaCloud\Vs;

/**
 * @method string getGbId()
 * @method $this withGbId($value)
 * @method string getLatitude()
 * @method $this withLatitude($value)
 * @method string getDescription()
 * @method $this withDescription($value)
 * @method string getType()
 * @method $this withType($value)
 * @method string getAutoStart()
 * @method $this withAutoStart($value)
 * @method string getParentId()
 * @method $this withParentId($value)
 * @method string getPassword()
 * @method $this withPassword($value)
 * @method string getVendor()
 * @method $this withVendor($value)
 * @method string getAlarmMethod()
 * @method $this withAlarmMethod($value)
 * @method string getDirectoryId()
 * @method $this withDirectoryId($value)
 * @method string getId()
 * @method $this withId($value)
 * @method string getShowLog()
 * @method $this withShowLog($value)
 * @method string getLongitude()
 * @method $this withLongitude($value)
 * @method string getGroupId()
 * @method $this withGroupId($value)
 * @method string getIp()
 * @method $this withIp($value)
 * @method string getOwnerId()
 * @method $this withOwnerId($value)
 * @method string getParams()
 * @method $this withParams($value)
 * @method string getUrl()
 * @method $this withUrl($value)
 * @method string getPort()
 * @method $this withPort($value)
 * @method string getName()
 * @method $this withName($value)
 * @method string getPosInterval()
 * @method $this withPosInterval($value)
 * @method string getUsername()
 * @method $this withUsername($value)
 * @method string getAutoPos()
 * @method $this withAutoPos($value)
 */
class ModifyDevice extends Rpc
{
}
